package factory

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// KickstartInstaller generates RHEL/Rocky Linux kickstart configuration files.
type KickstartInstaller struct{}

func init() {
	RegisterInstaller(&KickstartInstaller{})
}

func (k *KickstartInstaller) Method() string   { return "kickstart" }
func (k *KickstartInstaller) Filename() string { return "ks.cfg" }

func (k *KickstartInstaller) GenerateConfig(params InstallerParams) (string, error) {
	passwordHash, err := sha512Crypt(params.Password)
	if err != nil {
		return "", fmt.Errorf("generate password hash: %w", err)
	}

	useDHCP := params.BuildIP == ""

	data := kickstartData{
		Hostname:             params.Hostname,
		Username:             params.Username,
		PasswordHash:         passwordHash,
		PlainPassword:        params.Password,
		SSHPublicKey:         params.SSHPublicKey,
		Timezone:             params.Timezone,
		Locale:               params.Locale,
		Keyboard:             params.Keyboard,
		Packages:             params.ExtraPackages,
		OSVersion:            params.OSVersion,
		InterfaceName:        params.InterfaceName,
		BuildIP:              params.BuildIP,
		Netmask:              params.Netmask,
		Gateway:              params.Gateway,
		UseDHCP:              useDHCP,
		CloudInitDatasources: params.CloudInitDatasources,
		CloudInitExtraLines:  params.CloudInitExtraLines,
		PlatformServices:     params.PlatformServices,
	}

	tmpl, err := template.New("kickstart").Funcs(template.FuncMap{
		"join": strings.Join,
	}).Parse(kickstartTemplate)
	if err != nil {
		return "", fmt.Errorf("parse kickstart template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute kickstart template: %w", err)
	}

	return buf.String(), nil
}

// kickstartData holds parameters for generating kickstart configuration.
type kickstartData struct {
	Hostname      string
	Username      string
	PasswordHash  string
	PlainPassword string
	SSHPublicKey  string
	Timezone      string
	Locale        string
	Keyboard      string
	Packages      []string
	OSVersion     string // "9", "8", etc.
	InterfaceName string
	BuildIP       string
	Netmask       string
	Gateway       string
	UseDHCP       bool
	// Platform-injectable fields — no TargetType conditionals needed.
	// New hypervisors just implement Platform.InstallerHints().
	CloudInitDatasources string   // e.g. "[NoCloud, ConfigDrive, None]"
	CloudInitExtraLines  []string // e.g. ["disable_vmware_customization: false"]
	PlatformServices     []string // e.g. ["qemu-guest-agent"] or ["vmtoolsd"]
}

// kickstartTemplate - aligned with VMware packer-examples-for-vsphere
// Reference: github.com/vmware/packer-examples-for-vsphere/builds/linux/rocky/9/data/ks.pkrtpl.hcl
//
// IMPORTANT: This template contains ZERO platform conditionals. All platform-specific
// values (packages, services, datasources, extra cloud.cfg lines) are injected via
// InstallerParams from Platform.InstallerHints() and Platform.ProvisionerPackages().
// To add a new hypervisor, implement those methods — do NOT add if/else blocks here.
const kickstartTemplate = `# Kickstart configuration generated by Forgemill
# Based on VMware packer-examples-for-vsphere

### Install from CD-ROM only (avoid version conflicts with network repos)
### Additional packages installed in %post after reboot
cdrom

### Text mode install
text

### Accept EULA
eula --agreed

### Language and keyboard
lang {{.Locale}}
keyboard {{.Keyboard}}

### Timezone
timezone {{.Timezone}} --utc

### Network configuration
{{- if .UseDHCP}}
network --bootproto=dhcp --device=link --activate --onboot=on --hostname={{.Hostname}}
{{- else}}
network --bootproto=static --device=link --activate --onboot=on --ip={{.BuildIP}} --netmask={{.Netmask}} --gateway={{.Gateway}} --nameserver=8.8.8.8,1.1.1.1 --hostname={{.Hostname}}
{{- end}}

### Lock the root account
rootpw --lock

### Create build user with wheel group
user --name={{.Username}} --iscrypted --password={{.PasswordHash}} --groups=wheel

### Firewall - allow SSH
firewall --enabled --ssh

### Authentication - use SSSD profile (enables password auth)
authselect select sssd

### SELinux
selinux --enforcing

### Disk partitioning
zerombr
clearpart --all --initlabel
autopart --type=lvm

### Enable services including sshd
services --enabled=NetworkManager,sshd

### Skip X
skipx

### Packages - minimal core only (additional packages installed in %post)
%packages --ignoremissing --excludedocs
@core
-iwl*firmware
%end

### Post-install
%post --log=/root/ks-post.log

# Update package cache
dnf makecache

# Install required packages (platform-specific, injected by Platform.ProvisionerPackages)
dnf install -y sudo cloud-init{{range .Packages}} {{.}}{{end}}

# Enable platform-specific services (injected by Platform.InstallerHints)
{{- range .PlatformServices}}
systemctl enable {{.}} || true
{{- end}}

# Configure sudoers for build user
echo "{{.Username}} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/{{.Username}}
chmod 440 /etc/sudoers.d/{{.Username}}
sed -i "s/^.*requiretty/#Defaults requiretty/" /etc/sudoers

# Configure SSH - enable password authentication
# This is critical for Packer to connect
sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/^#*PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config

# Also set in sshd_config.d for RHEL 9+ compatibility
mkdir -p /etc/ssh/sshd_config.d
cat > /etc/ssh/sshd_config.d/50-forgemill.conf << 'SSHEOF'
PasswordAuthentication yes
PermitRootLogin no
PubkeyAuthentication yes
SSHEOF

# Configure cloud-init to allow password auth
if [ -f /etc/cloud/cloud.cfg ]; then
    sed -i 's/^ssh_pwauth:.*/ssh_pwauth: true/' /etc/cloud/cloud.cfg
    # Also ensure it's set if line doesn't exist
    grep -q "^ssh_pwauth:" /etc/cloud/cloud.cfg || echo "ssh_pwauth: true" >> /etc/cloud/cloud.cfg
fi

# Cloud-init datasource configuration (injected by Platform.InstallerHints)
cat > /etc/cloud/cloud.cfg.d/90-datasource.cfg << 'DSEOF'
datasource_list: {{.CloudInitDatasources}}
DSEOF
{{- range .CloudInitExtraLines}}
# Platform-specific cloud.cfg line (injected by Platform.InstallerHints)
grep -q "{{.}}" /etc/cloud/cloud.cfg 2>/dev/null || echo "{{.}}" >> /etc/cloud/cloud.cfg
{{- end}}

{{- if .SSHPublicKey}}
# SSH authorized keys
mkdir -p /home/{{.Username}}/.ssh
echo '{{.SSHPublicKey}}' > /home/{{.Username}}/.ssh/authorized_keys
chmod 700 /home/{{.Username}}/.ssh
chmod 600 /home/{{.Username}}/.ssh/authorized_keys
chown -R {{.Username}}:{{.Username}} /home/{{.Username}}/.ssh
{{- end}}

%end

### Reboot after install
reboot --eject
`
